services:
  db:
    container_name: servicehub-web
    image: postgres:15
    environment:
      POSTGRES_DB: servicehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: servicehub-db
    build: .
    command: sh -c "
      python src/manage.py migrate &&
      sh scripts/load_initial_data.sh &&
      python src/manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      MODE: prod
      POSTGRES_DB: servicehub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
